#!/bin/sh

# Make sure we’re using the latest Homebrew
echo "Update HomeBrew"
brew update
echo "Done."

# Upgrade any already-installed formulae
echo "Upgrade Homebrew"
brew upgrade
echo "Done."

# Install wget with IRI support
echo "Install wget"
brew install wget --enable-iri
echo "Done."

# cask to install other mac app
echo "Install cask"
brew install caskroom/cask/brew-cask
echo "Done."

# Install other useful binaries
echo "Install ACK"
brew install ack
echo "Done."

echo "Install git"
brew install git
echo "Done."

echo "Install node"
brew install node # This installs `npm` too using the recommended installation method
echo "Done."

# Remove outdated versions from the cellar
echo "Cleanup"
brew cleanup
echo "Done."